### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by dawnwages** [dawnwages/TheUltimateGame#1]
We need to get people logged tf in

**Comment by stoversa** [comment]
We will likely be working with Passport JS for this US: http://www.passportjs.org/

**Comment by stoversa** [comment]
Team: I'm working on our authentication in my fork: [https://github.com/stoversa/TheUltimateGame](https://github.com/stoversa/TheUltimateGame).

**Comment by stoversa** [comment]
Pull request #11 should have implemented this. Ready for QA!
